---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: my-attendee-service

outputs:
- name: package-output

run:
  path: my-attendee-service/ci/tasks/package.sh

