---
resources:
- name: my-attendee-service
  type: git
  source:
    uri: https://github.com/kishore-diyyana/pcf-attendee-service-code   #<----- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.sys.pikes.pal.pivotal.io       #<----- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: kdiyyana-pal    #<----- REPLACE ME
    space: sandbox         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: my-attendee-service
  - task: package
    file: my-attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: my-attendee-service/manifest.yml
      path: package-output/attendee-service.jar

